name: Deploy

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Install apm (with Atom)
      env:
        TEMP_DEB: atom-amd64.deb
      run: |
        wget -nv -O "$TEMP_DEB" https://atom.io/download/deb &&
        sudo apt -qq install "$TEMP_DEB"
        rm -f "$TEMP_DEB"
        apm --version

    - name: Checkout repo
      uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
      with:
        submodules: true

    - name: Check release version matches package.json
      env:
        GH_REF: ${{ github.ref }}
      shell: node {0}
      run: |
        const matches = process.env.GH_REF.match(/refs\/tags\/v(.+)/);
        if (matches) {
          const releaseVer = matches[1];
          const packageVer = JSON.parse(fs.readFileSync('package.json')).version;
          if (releaseVer === packageVer) {
            console.log('Version: ${releaseVer}');
          } else {
            setFailed(`Release version (${releaseVer}) does not match package.json version (${packageVer})`);
          }
        } else {
          setFailed(`No tag detected in ref: '${process.env.GH_REF}'`);
        }

        function setFailed(msg) {
          console.log(msg); process.exitCode = 1;
        }

    - name: Publish
      env:
        TOKEN: ${{ secrets.ATOM_TOKEN }}
      run: |
        apm login --token "$TOKEN"
        apm publish --tag "$VERSION_TAG"

    - name: Delete tag on failure
      if: failure()
      run: |
        git push origin :${{ github.ref }}
        echo "The GitHub release has been relegated to a draft and can be republished when the problems are fixed"
